// Class automatically generated by Dev-C++ New Class wizard

#include "graphicsfxpostprocessing.h" // class's header file

// class constructor
graphicsFxPostProcessing::graphicsFxPostProcessing()
{
    saved_time = 0;
}

// class destructor
graphicsFxPostProcessing::~graphicsFxPostProcessing()
{
}

void graphicsFxPostProcessing :: initialize()
{
} 

void graphicsFxPostProcessing :: handler(BITMAP* input_buffer, BITMAP* output_buffer, unsigned int time)
{
}
