// Class automatically generated by Dev-C++ New Class wizard

#ifndef KEYBOARDMAP_H
#define KEYBOARDMAP_H

#include <allegro.h>
#include <map>
#include <string>

#include "defines.h"

using namespace std;

/*
 * Map keys
 */
class keyboardMap
{
  private:
    map<string, unsigned int> keys;
    
  public:
    keyboardMap();  		// class constructor
	~keyboardMap();         // class destructor
	
	inline unsigned int GetKey(string n) { return keys[n]; }
};

#endif // KEYBOARDMAP_H
