// Class automatically generated by Dev-C++ New Class wizard

#include "mundo.h" // class's header file

// class constructor
mundo::mundo()
{
}

mundo::mundo(char *file)
{
    cout << file << endl;
    screen_orig_x = 0;
    screen_orig_y = 0;
    screen_tiles_x = 0;
    screen_tiles_y = 0;
    tiles_orig_x  = 0;
    tiles_orig_y  = 0;
    tiles_m_x     = 0;
    tiles_m_y     = 0;
    tiles_size_x  = 0;
    tiles_size_y  = 0;
    tiles_in_tiles_image_x = 0;
    
    io.obrirFitxer(file, 0);
    io.llegirParaula(buffer);            // Name
    io.llegirParaula(buffer);            // Name value
    io.llegirParaula(buffer);            // Image
    io.llegirParaula(path_world_image);  // Image path
    io.llegirParaula(buffer);            // screen_x
    io.llegirEnter(&screen_orig_x);      // screen_x value
    io.llegirParaula(buffer);            // screen_y
    io.llegirEnter(&screen_orig_y);      // screen_y value
    io.llegirParaula(buffer);            // tiles_orig_size_x
    io.llegirEnter(&tiles_orig_x);       // tiles_orig_size_x value
    io.llegirParaula(buffer);            // tiles_orig_size_y
    io.llegirEnter(&tiles_orig_y);       // tiles_orig_size_y value
    io.llegirParaula(buffer);            // screen_tiles_x
    io.llegirEnter(&screen_tiles_x);     // screen_tiles_x value
    io.llegirParaula(buffer);            // screen_tiles_y     
    io.llegirEnter(&screen_tiles_y);     // screen_tiles_y value     
    io.llegirParaula(buffer);            // tiles_size_x
    io.llegirEnter(&tiles_size_x);       // tiles_size_x value
    io.llegirParaula(buffer);            // tiles_size_y
    io.llegirEnter(&tiles_size_y);       // tiles_size_y value  
    io.llegirParaula(buffer);            // num_scroll_planes
    io.llegirEnter(&num_scroll_planes);  // num_scroll_planes value
    scroll_planes = new BITMAP*[num_scroll_planes];
    scroll_size_x = new int[num_scroll_planes];
    scroll_size_y = new int[num_scroll_planes];
    for( int i = 0 ; i < num_scroll_planes ; i++ )
    {
        io.llegirParaula(buffer);        // scroll
        io.llegirParaula(buffer);        // scroll_path        
        //scroll_planes[i] = load_bmp(buffer, pal);
        io.llegirParaula(buffer);        // scroll_size_x
        io.llegirEnter(&scroll_size_x[i]);  // scroll_size_x value
        io.llegirParaula(buffer);        // scroll_size_y
        io.llegirEnter(&scroll_size_y[i]);  // scroll_size_y value
    }    
   
    cout << path_world_image << endl;
      
    world_image = load_bmp(path_world_image, pal);    
    cout << " 1 " << endl << endl;
     
    tiles_m_x = screen_orig_x / tiles_orig_x;
    tiles_m_y = screen_orig_y / tiles_orig_y;
     
    tiles_mundo = new int*[tiles_m_y];
    for( int i = 0 ; i < tiles_m_y ; i++ )
    {
        tiles_mundo[i] = new int[tiles_m_x];
    }

    io.llegirParaula(buffer);
    for( int i = 0 ; i < tiles_m_y ; i++ )
    {
        for( int j = 0 ; j < tiles_m_x ; j++ )
        {
            int val;
            io.llegirEnter(&val);
            tiles_mundo[i][j] = val;
        }         
    }    
    
    screen_new_x = tiles_m_x * tiles_size_x;
    screen_new_y = tiles_m_y * tiles_size_y;
    cout << screen_new_x << " - " << screen_new_y << endl;
    cout << " all OK " << endl;
}

// class destructor
mundo::~mundo()
{
	// insert your code here
}

int mundo::GetTileValueByCoord(int x, int y)
{
    int tile_x = div(x, tiles_size_x).quot;
    int tile_y = div(y, tiles_size_y).quot;
 
    assert( tile_x < tiles_m_x && tile_x >= 0);   
    assert( tile_y < tiles_m_y && tile_y >= 0);

    return tiles_mundo[tile_y][tile_x];
}
