// Class automatically generated by Dev-C++ New Class wizard

#include "phase_info.h" // class's header file

// class constructor
phase_info::phase_info()
{
}

// class destructor
phase_info::~phase_info()
{
}

void phase_info::readPhaseInfo(char* file)
{
     char buffer[80];
     
     io.obrirFitxer(file, LECTURA);
     
     io.llegirParaula(buffer); // x_ini
     io.llegirEnter(&x_ini);
     io.llegirParaula(buffer); // y_ini
     io.llegirEnter(&y_ini);
     io.llegirParaula(buffer); // warrior_form
     io.llegirEnter(&warrior_form);     
     io.llegirParaula(buffer); // warrior_prev_state
     io.llegirEnter(&warrior_prev_state);
     io.llegirParaula(buffer); // warrior_ini_state
     io.llegirEnter(&warrior_ini_state);     
     io.llegirParaula(buffer); // dir
     io.llegirEnter(&warrior_dir);          
     io.llegirParaula(buffer); // song
     io.llegirParaula(song);
     io.llegirParaula(buffer); // world_description
     io.llegirParaula(world_description);
     io.llegirParaula(buffer); // enemies_description
     io.llegirParaula(enemies_description);
     io.llegirParaula(buffer); // chk_description
     io.llegirParaula(chk_description);
     io.llegirParaula(buffer); // scripts
     io.llegirParaula(scripts);
     io.llegirParaula(buffer); // objects
     io.llegirParaula(objects);     
     io.llegirParaula(buffer); // scrolls
     io.llegirParaula(scrolls);               
     io.llegirParaula(buffer); // scrolls
     io.llegirParaula(anims);   
}
