// Class automatically generated by Dev-C++ New Class wizard

#ifndef SCRIPTHANDLER_H
#define SCRIPTHANDLER_H

#include <list>

#include "symbolTable.h"
#include "script.h"
#include "entradaSortida.h"


class scriptHandler
{
  private:
    symbolTablePtr smbTable;
    list<script*> scripts;
    
  public:		
    scriptHandler(symbolTablePtr smbTable);       // class constructor
	~scriptHandler();                             // class destructor
	
	bool ReadScriptsFile(char* file);
	void SaveScriptsFile(char* file);
	
	void AnalyzeScripts(int x, int y, int xSize, int ySize);
	
	inline void AddNewScript(script* scrpt) { scripts.push_back(scrpt); }

	inline list<script*>* GetScripts() { return &scripts; }

};

#endif // SCRIPTHANDLER_H
