// Class automatically generated by Dev-C++ New Class wizard

#include "static_image.h" // class's header file

// class constructor
static_image::static_image()
{
	// insert your code here
}

// class destructor
static_image::~static_image()
{
    destroy_bitmap(image);
}

void static_image::openImage(const char *file, int screenX, int screenY)
{     
     image = load_bmp(file, NULL);  
     sizeX = screenX;
     sizeY = screenY;   
}

BITMAP *static_image::getImage()
{
    return image;
}
