// Class automatically generated by Dev-C++ New Class wizard

#ifndef TIMER_H
#define TIMER_H

#include <allegro.h>
#include <iostream.h>

/*
 * No description
 */
class Timer
{
	public:
		Timer();
		~Timer();
		
		void init(int speed)
		{
            install_param_int(callback, (void*)this, speed);
        }
        inline unsigned int getMseg()
        {
            return mseg;
        }
        inline unsigned int getMsegGlobal()
        {
            return mseg_global;
        }
        inline void setMseg(unsigned int n)
        {
             mseg = n;
        }
        
        
    private:        
        unsigned int mseg;
        unsigned int mseg_global;        
        
        void tick()
        {
             mseg++;
             mseg_global++;
        }
        
        static void callback(void* param)
        {
            ((Timer*)param)->tick();
        }                
};

#endif // TIMER_H
