// Class automatically generated by Dev-C++ New Class wizard

#include "timer.h" // class's header file

// class constructor
Timer::Timer()
{
    mseg = 0;
    mseg_global = 0;
}

// class destructor
Timer::~Timer()
{
	// insert your code here
}


