// Class automatically generated by Dev-C++ New Class wizard

#ifndef WATERGRAPHICFX_H
#define WATERGRAPHICFX_H

#include "graphicsfxpostprocessing.h" // inheriting class's header file

/*
 * No description
 */
class waterGraphicFx : public graphicsFxPostProcessing
{
  private:
    unsigned int waterFrames;
    unsigned int maxWaterDisp;
    unsigned int transitionTime;
    unsigned int savedTime;
    unsigned int frameSizeY;          // SCREEN_Y/FRAMES_AGUA
    unsigned int *waterFramePosition;
    
  public:
    waterGraphicFx();    		// class constructor
	~waterGraphicFx();          // class destructor
	
	void initialize(unsigned int wf, unsigned int mwd, unsigned int tt);
	void handler(BITMAP* input_buffer, BITMAP* output_buffer, unsigned int output_bitmap_size_x, unsigned int output_bitmap_size_y, unsigned int time);
};

#endif // WATERGRAPHICFX_H
