// Class automatically generated by Dev-C++ New Class wizard

#include "animation.h" // class's header file

// class constructor
animation::animation()
{
	// insert your code here
}

// class destructor
animation::~animation()
{
    for( list<sprite_ptr>::iterator it = sprites.begin() ; it != sprites.end() ; it++ )
    {
        delete *it;
    }
    sprites.clear();
}
