// Class automatically generated by Dev-C++ New Class wizard

#ifndef ANIMATION_H
#define ANIMATION_H

#include "sprite.h" // inheriting class's header file
#include <list>

using namespace std;

/*
 * No description
 */
class animation
{
  public:
    list<sprite_ptr> sprites;
    int              numSprites;
    int              velocidad;

  public:
	animation();    // class constructor
	~animation();   // class destructor
};

#endif // ANIMATION_H
