// Class automatically generated by Dev-C++ New Class wizard

#ifndef FXHANDLER_H
#define FXHANDLER_H

#include <string.h>
#include <allegro.h>
#include <vector>
#include <assert.h>

using namespace std;

class sound
{
  private:
    bool destroyable;
    char name[100];
    SAMPLE* sample;
    bool enabled;
    bool loop;
     
  public:
    sound(char *n, bool loop);
    ~sound();
    
    void play();
    void stop();
    
    inline void setEnabled(bool s) { enabled = s;    }
    inline bool getEnabled()       { return enabled; }   
    
};

class fxHandler
{
  private:
    int            numSounds;
    char           *system;
    vector<sound*> sounds;
    char           *channel;
    char           result;
    unsigned int   version;
       
  public:	
    fxHandler();  	// class constructor
    ~fxHandler();   // class destructor    
    
    int addSound(char *name, bool loop);

    void playSound(int numSound);
    void stopSound(int numSound);
    
    bool getEnabled(int numSound);
    void setEnabled(int numSound, bool s);

};

#endif // FXHANDLER_H
