// Class automatically generated by Dev-C++ New Class wizard

#include "fxhandler.h" // class's header file

sound :: sound(char *n, bool _loop)
{  
    enabled = false;
    
    strcpy(name, n);
    loop = _loop;
    printf("Loaded sound %s\n", name);
    sample = load_sample(name);
    assert(sample);
}
sound :: ~sound() {
    destroy_sample(sample);
}

void sound :: play() {
  assert(play_sample(sample, 255, 128, 1000, loop) >= 0);
}

void sound :: stop() {
  stop_sample(sample);
}

// class constructor
fxHandler::fxHandler() {
    // Sound is initialized in the main
    numSounds = 0;
}

// class destructor
fxHandler::~fxHandler() {
}

int fxHandler :: addSound(char *name, bool loop)
{
    sound* newSound = new sound(name, loop);
    assert( newSound != NULL);
    sounds.push_back(newSound);
    numSounds++;

    return numSounds - 1;
}

void fxHandler :: playSound(int numSound)
{
    sounds[numSound]->play();
}

void fxHandler :: stopSound(int numSound)
{
    sounds[numSound]->stop();
}

bool fxHandler :: getEnabled(int numSound)
{
    sounds[numSound]->getEnabled();
}

void fxHandler :: setEnabled(int numSound, bool s)
{
    sounds[numSound]->setEnabled(s);
}
