// Class automatically generated by Dev-C++ New Class wizard

#ifndef FXHANDLER_H
#define FXHANDLER_H

#include <string.h>
#include <allegro.h>
#include <fmod.h>
#include <iostream.h>
#include <vector>

using namespace std;

class sound
{
  private:
    FMOD_SYSTEM *system;
    bool destroyable;
    char name[100];
    FMOD_SOUND *fmodSound;         
    FMOD_CHANNEL *channel;   
    bool enabled;
    bool loop;
  
    void init();
    void destroy();
    
  public:
    sound(FMOD_SYSTEM *sys, char *n, bool destroy, bool loop);
    ~sound();
    
    void play();
    
    inline void setEnabled(bool s) { enabled = s;    }
    inline bool getEnabled()       { return enabled; }
    
    inline FMOD_CHANNEL* getChannel() { return channel; }
    
    
};

class fxHandler
{
  private:
    int numSounds;
    FMOD_SYSTEM       *system;
    vector<sound*>     sounds;
    FMOD_CHANNEL      *channel;
    FMOD_RESULT       result;
    unsigned int      version;
       
  public:	
    fxHandler();  	// class constructor
    ~fxHandler();   // class destructor    
    
    int addSound(char *name, bool destroyable, bool loop);
    void playSound(int numSound);
    void stopSound(int numSound);
    
    bool getEnabled(int numSound);
    void setEnabled(int numSound, bool s);

};

#endif // FXHANDLER_H
