// Class automatically generated by Dev-C++ New Class wizard

#ifndef FXHANDLER_H
#define FXHANDLER_H

#include <string.h>
#include <allegro.h>
#include <vector>
#include <assert.h>

using namespace std;

class sound
{
  private:
    //FMOD_SYSTEM *system;
    char *system;
    bool destroyable;
    char name[100];
    char *fmodSound;         
    char *channel;   
    bool enabled;
    bool loop;
  
    void init();
    void destroy();
    
  public:
    sound(char *sys, char *n, bool destroy, bool loop);
    ~sound();
    
    void play();
    
    inline void setEnabled(bool s) { enabled = s;    }
    inline bool getEnabled()       { return enabled; }
    
    inline char* getChannel() { return channel; }
    
    
};

class fxHandler
{
  private:
    int numSounds;
    char       *system;
    vector<sound*>     sounds;
    char      *channel;
    char       result;
    unsigned int      version;
       
  public:	
    fxHandler();  	// class constructor
    ~fxHandler();   // class destructor    
    
    int addSound(char *name, bool destroyable, bool loop);
    void playSound(int numSound);
    void stopSound(int numSound);
    
    bool getEnabled(int numSound);
    void setEnabled(int numSound, bool s);

};

#endif // FXHANDLER_H
