// Class automatically generated by Dev-C++ New Class wizard

#include "keyboardmap.h" // class's header file

// class constructor
keyboardMap::keyboardMap()
{
    //default keys
    keys["UP"]     = UP;
    keys["DOWN"]   = DOWN;
    keys["LEFT"]   = LEFT;
    keys["RIGHT"]  = RIGHT;
    keys["FIRE"]   = FIRE;
    keys["NO_KEY"] = NO_KEY;
}

// class destructor
keyboardMap::~keyboardMap()
{

}
