// Class automatically generated by Dev-C++ New Class wizard

#ifndef SCRIPT_H
#define SCRIPT_H

#include <allegro.h>
#include <string>
#include "defines.h"
#include <iostream>

#include "symboltable.h"
/*
/*
 * No description
 */
typedef class script script_ptr;
class script
{
  private:
    int coordX;
    int coordY;
    int sizeX;
    int sizeY;          
          
    map<string, unsigned int> inputVars;
    map<string, unsigned int> outputVars;

    symbolTablePtr smbTable;
     
  public:
	script(symbolTablePtr smbTable);    // class constructor
	~script();   // class destructor

   inline int GetX()     { return coordX; }
   inline int GetY()     { return coordY; }
   inline int GetSizeX() { return sizeX;  }
   inline int GetSizeY() { return sizeY;  }
   
   inline map<string, unsigned int>* GetInputVars()  { return &inputVars;  }
   inline map<string, unsigned int>* GetOutputVars() { return &outputVars; }
   
   inline void SetX(int x)      { coordX = x; }
   inline void SetY(int y)      { coordY = y; }
   inline void SetSizeX(int sx) { sizeX = sx; }
   inline void SetSizeY(int sy) { sizeY = sy; }
   
   void addTriggerCoords(int x, int y, int size_x, int size_y);
   void addNewInputVar(string name, unsigned int value);
   void addNewOutputVar(string name, unsigned int value);
   

   bool checkInputVars();
   bool updateOutputVars();
};
#endif // SCRIPT_H
