// Class automatically generated by Dev-C++ New Class wizard

#ifndef SPRITE_H
#define SPRITE_H

#include<vector.h>
#include <allegro.h>
#include "static_image.h"

/*
 * No description
 */
typedef class sprite* sprite_ptr; 
class sprite
{
  public:
    static_image *sourceImage;          
    vector<sprite_ptr> internalSprites;
    int    xUpLeft;
    int    yUpLeft;
    int    xDownRight;
    int    yDownRight;
    int    xSize;
    int    ySize;
    int    state;
    int    numComponents;
    
  public:    
	sprite();    // class constructor	
	~sprite();   // class desructor
	
	void newSprite(static_image *bitmapFile, int upLeftX, int upLeftY, int downRightX, int downRightY, int estat, int numComponets);
	static_image* getSourceImage();
	
	void AddInternalSprite(static_image *bitmapFile, int upLeftX, int upLeftY, int downRightX, int downRightY);
	static_image* getInternalSprite(int i);
	
};

#endif // SPRITE_H
