// Class automatically generated by Dev-C++ New Class wizard

#ifndef STATIC_IMAGE_H
#define STATIC_IMAGE_H

#include <allegro.h>
#include "defines.h"
#include <iostream.h>

/*
 * No description
 */
class static_image
{
  private:
    BITMAP *image;
    int    sizeX;
    int    sizeY;

  public:
	static_image();    // class constructor
	~static_image();   // class destructor

	void    openImage(const char* file, int screenX, int screenY);
	BITMAP* getImage();
};

#endif // STATIC_IMAGE_H
