// Class automatically generated by Dev-C++ New Class wizard

#include "symboltable.h" // class's header file

// class constructor
symbolTable::symbolTable()
{
}

// class destructor
symbolTable::~symbolTable()
{
}

void symbolTable :: EraseElement(string key)
{
     table.erase(key);
}
